
package com.ebay.soap.eBLBaseComponents;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "eBayAPIInterface", targetNamespace = "urn:ebay:apis:eBLBaseComponents")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EBayAPIInterface {


    /**
     * 
     * @param addFixedPriceItemRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.AddFixedPriceItemResponseType
     */
    @WebMethod(operationName = "AddFixedPriceItem")
    @WebResult(name = "AddFixedPriceItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddFixedPriceItemResponse")
    public AddFixedPriceItemResponseType addFixedPriceItem(
        @WebParam(name = "AddFixedPriceItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddFixedPriceItemRequest")
        AddFixedPriceItemRequestType addFixedPriceItemRequest);

    /**
     * 
     * @param addItemRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.AddItemResponseType
     */
    @WebMethod(operationName = "AddItem")
    @WebResult(name = "AddItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddItemResponse")
    public AddItemResponseType addItem(
        @WebParam(name = "AddItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddItemRequest")
        AddItemRequestType addItemRequest);

    /**
     * 
     * @param addItemsRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.AddItemsResponseType
     */
    @WebMethod(operationName = "AddItems")
    @WebResult(name = "AddItemsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddItemsResponse")
    public AddItemsResponseType addItems(
        @WebParam(name = "AddItemsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddItemsRequest")
        AddItemsRequestType addItemsRequest);

    /**
     * 
     * @param addMemberMessageAAQToPartnerRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.AddMemberMessageAAQToPartnerResponseType
     */
    @WebMethod(operationName = "AddMemberMessageAAQToPartner")
    @WebResult(name = "AddMemberMessageAAQToPartnerResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddMemberMessageAAQToPartnerResponse")
    public AddMemberMessageAAQToPartnerResponseType addMemberMessageAAQToPartner(
        @WebParam(name = "AddMemberMessageAAQToPartnerRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddMemberMessageAAQToPartnerRequest")
        AddMemberMessageAAQToPartnerRequestType addMemberMessageAAQToPartnerRequest);

    /**
     * 
     * @param addMemberMessageRTQRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.AddMemberMessageRTQResponseType
     */
    @WebMethod(operationName = "AddMemberMessageRTQ")
    @WebResult(name = "AddMemberMessageRTQResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddMemberMessageRTQResponse")
    public AddMemberMessageRTQResponseType addMemberMessageRTQ(
        @WebParam(name = "AddMemberMessageRTQRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddMemberMessageRTQRequest")
        AddMemberMessageRTQRequestType addMemberMessageRTQRequest);

    /**
     * 
     * @param addMemberMessagesAAQToBidderRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.AddMemberMessagesAAQToBidderResponseType
     */
    @WebMethod(operationName = "AddMemberMessagesAAQToBidder")
    @WebResult(name = "AddMemberMessagesAAQToBidderResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddMemberMessagesAAQToBidderResponse")
    public AddMemberMessagesAAQToBidderResponseType addMemberMessagesAAQToBidder(
        @WebParam(name = "AddMemberMessagesAAQToBidderRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddMemberMessagesAAQToBidderRequest")
        AddMemberMessagesAAQToBidderRequestType addMemberMessagesAAQToBidderRequest);

    /**
     * 
     * @param addOrderRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.AddOrderResponseType
     */
    @WebMethod(operationName = "AddOrder")
    @WebResult(name = "AddOrderResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddOrderResponse")
    public AddOrderResponseType addOrder(
        @WebParam(name = "AddOrderRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddOrderRequest")
        AddOrderRequestType addOrderRequest);

    /**
     * 
     * @param addSecondChanceItemRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.AddSecondChanceItemResponseType
     */
    @WebMethod(operationName = "AddSecondChanceItem")
    @WebResult(name = "AddSecondChanceItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddSecondChanceItemResponse")
    public AddSecondChanceItemResponseType addSecondChanceItem(
        @WebParam(name = "AddSecondChanceItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddSecondChanceItemRequest")
        AddSecondChanceItemRequestType addSecondChanceItemRequest);

    /**
     * 
     * @param addToItemDescriptionRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.AddToItemDescriptionResponseType
     */
    @WebMethod(operationName = "AddToItemDescription")
    @WebResult(name = "AddToItemDescriptionResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddToItemDescriptionResponse")
    public AddToItemDescriptionResponseType addToItemDescription(
        @WebParam(name = "AddToItemDescriptionRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddToItemDescriptionRequest")
        AddToItemDescriptionRequestType addToItemDescriptionRequest);

    /**
     * 
     * @param addToWatchListRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.AddToWatchListResponseType
     */
    @WebMethod(operationName = "AddToWatchList")
    @WebResult(name = "AddToWatchListResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddToWatchListResponse")
    public AddToWatchListResponseType addToWatchList(
        @WebParam(name = "AddToWatchListRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddToWatchListRequest")
        AddToWatchListRequestType addToWatchListRequest);

    /**
     * 
     * @param completeSaleRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.CompleteSaleResponseType
     */
    @WebMethod(operationName = "CompleteSale")
    @WebResult(name = "CompleteSaleResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "CompleteSaleResponse")
    public CompleteSaleResponseType completeSale(
        @WebParam(name = "CompleteSaleRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "CompleteSaleRequest")
        CompleteSaleRequestType completeSaleRequest);

    /**
     * 
     * @param confirmIdentityRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.ConfirmIdentityResponseType
     */
    @WebMethod(operationName = "ConfirmIdentity")
    @WebResult(name = "ConfirmIdentityResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ConfirmIdentityResponse")
    public ConfirmIdentityResponseType confirmIdentity(
        @WebParam(name = "ConfirmIdentityRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ConfirmIdentityRequest")
        ConfirmIdentityRequestType confirmIdentityRequest);

    /**
     * 
     * @param deleteMyMessagesRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.DeleteMyMessagesResponseType
     */
    @WebMethod(operationName = "DeleteMyMessages")
    @WebResult(name = "DeleteMyMessagesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "DeleteMyMessagesResponse")
    public DeleteMyMessagesResponseType deleteMyMessages(
        @WebParam(name = "DeleteMyMessagesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "DeleteMyMessagesRequest")
        DeleteMyMessagesRequestType deleteMyMessagesRequest);

    /**
     * 
     * @param endFixedPriceItemRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.EndFixedPriceItemResponseType
     */
    @WebMethod(operationName = "EndFixedPriceItem")
    @WebResult(name = "EndFixedPriceItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "EndFixedPriceItemResponse")
    public EndFixedPriceItemResponseType endFixedPriceItem(
        @WebParam(name = "EndFixedPriceItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "EndFixedPriceItemRequest")
        EndFixedPriceItemRequestType endFixedPriceItemRequest);

    /**
     * 
     * @param endItemRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.EndItemResponseType
     */
    @WebMethod(operationName = "EndItem")
    @WebResult(name = "EndItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "EndItemResponse")
    public EndItemResponseType endItem(
        @WebParam(name = "EndItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "EndItemRequest")
        EndItemRequestType endItemRequest);

    /**
     * 
     * @param endItemsRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.EndItemsResponseType
     */
    @WebMethod(operationName = "EndItems")
    @WebResult(name = "EndItemsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "EndItemsResponse")
    public EndItemsResponseType endItems(
        @WebParam(name = "EndItemsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "EndItemsRequest")
        EndItemsRequestType endItemsRequest);

    /**
     * 
     * @param extendSiteHostedPicturesRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.ExtendSiteHostedPicturesResponseType
     */
    @WebMethod(operationName = "ExtendSiteHostedPictures")
    @WebResult(name = "ExtendSiteHostedPicturesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ExtendSiteHostedPicturesResponse")
    public ExtendSiteHostedPicturesResponseType extendSiteHostedPictures(
        @WebParam(name = "ExtendSiteHostedPicturesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ExtendSiteHostedPicturesRequest")
        ExtendSiteHostedPicturesRequestType extendSiteHostedPicturesRequest);

    /**
     * 
     * @param fetchTokenRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.FetchTokenResponseType
     */
    @WebMethod(operationName = "FetchToken")
    @WebResult(name = "FetchTokenResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "FetchTokenResponse")
    public FetchTokenResponseType fetchToken(
        @WebParam(name = "FetchTokenRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "FetchTokenRequest")
        FetchTokenRequestType fetchTokenRequest);

    /**
     * 
     * @param getAccountRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetAccountResponseType
     */
    @WebMethod(operationName = "GetAccount")
    @WebResult(name = "GetAccountResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetAccountResponse")
    public GetAccountResponseType getAccount(
        @WebParam(name = "GetAccountRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetAccountRequest")
        GetAccountRequestType getAccountRequest);

    /**
     * 
     * @param getAdFormatLeadsRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetAdFormatLeadsResponseType
     */
    @WebMethod(operationName = "GetAdFormatLeads")
    @WebResult(name = "GetAdFormatLeadsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetAdFormatLeadsResponse")
    public GetAdFormatLeadsResponseType getAdFormatLeads(
        @WebParam(name = "GetAdFormatLeadsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetAdFormatLeadsRequest")
        GetAdFormatLeadsRequestType getAdFormatLeadsRequest);

    /**
     * 
     * @param getAllBiddersRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetAllBiddersResponseType
     */
    @WebMethod(operationName = "GetAllBidders")
    @WebResult(name = "GetAllBiddersResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetAllBiddersResponse")
    public GetAllBiddersResponseType getAllBidders(
        @WebParam(name = "GetAllBiddersRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetAllBiddersRequest")
        GetAllBiddersRequestType getAllBiddersRequest);

    /**
     * 
     * @param getBestOffersRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetBestOffersResponseType
     */
    @WebMethod(operationName = "GetBestOffers")
    @WebResult(name = "GetBestOffersResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetBestOffersResponse")
    public GetBestOffersResponseType getBestOffers(
        @WebParam(name = "GetBestOffersRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetBestOffersRequest")
        GetBestOffersRequestType getBestOffersRequest);

    /**
     * 
     * @param getBidderListRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetBidderListResponseType
     */
    @WebMethod(operationName = "GetBidderList")
    @WebResult(name = "GetBidderListResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetBidderListResponse")
    public GetBidderListResponseType getBidderList(
        @WebParam(name = "GetBidderListRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetBidderListRequest")
        GetBidderListRequestType getBidderListRequest);

    /**
     * 
     * @param getCategoriesRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetCategoriesResponseType
     */
    @WebMethod(operationName = "GetCategories")
    @WebResult(name = "GetCategoriesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetCategoriesResponse")
    public GetCategoriesResponseType getCategories(
        @WebParam(name = "GetCategoriesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetCategoriesRequest")
        GetCategoriesRequestType getCategoriesRequest);

    /**
     * 
     * @param getCategoryFeaturesRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetCategoryFeaturesResponseType
     */
    @WebMethod(operationName = "GetCategoryFeatures")
    @WebResult(name = "GetCategoryFeaturesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetCategoryFeaturesResponse")
    public GetCategoryFeaturesResponseType getCategoryFeatures(
        @WebParam(name = "GetCategoryFeaturesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetCategoryFeaturesRequest")
        GetCategoryFeaturesRequestType getCategoryFeaturesRequest);

    /**
     * 
     * @param getCategoryMappingsRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetCategoryMappingsResponseType
     */
    @WebMethod(operationName = "GetCategoryMappings")
    @WebResult(name = "GetCategoryMappingsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetCategoryMappingsResponse")
    public GetCategoryMappingsResponseType getCategoryMappings(
        @WebParam(name = "GetCategoryMappingsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetCategoryMappingsRequest")
        GetCategoryMappingsRequestType getCategoryMappingsRequest);

    /**
     * 
     * @param getChallengeTokenRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetChallengeTokenResponseType
     */
    @WebMethod(operationName = "GetChallengeToken")
    @WebResult(name = "GetChallengeTokenResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetChallengeTokenResponse")
    public GetChallengeTokenResponseType getChallengeToken(
        @WebParam(name = "GetChallengeTokenRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetChallengeTokenRequest")
        GetChallengeTokenRequestType getChallengeTokenRequest);

    /**
     * 
     * @param getDescriptionTemplatesRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetDescriptionTemplatesResponseType
     */
    @WebMethod(operationName = "GetDescriptionTemplates")
    @WebResult(name = "GetDescriptionTemplatesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetDescriptionTemplatesResponse")
    public GetDescriptionTemplatesResponseType getDescriptionTemplates(
        @WebParam(name = "GetDescriptionTemplatesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetDescriptionTemplatesRequest")
        GetDescriptionTemplatesRequestType getDescriptionTemplatesRequest);

    /**
     * 
     * @param getFeedbackRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetFeedbackResponseType
     */
    @WebMethod(operationName = "GetFeedback")
    @WebResult(name = "GetFeedbackResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetFeedbackResponse")
    public GetFeedbackResponseType getFeedback(
        @WebParam(name = "GetFeedbackRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetFeedbackRequest")
        GetFeedbackRequestType getFeedbackRequest);

    /**
     * 
     * @param getItemRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetItemResponseType
     */
    @WebMethod(operationName = "GetItem")
    @WebResult(name = "GetItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetItemResponse")
    public GetItemResponseType getItem(
        @WebParam(name = "GetItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetItemRequest")
        GetItemRequestType getItemRequest);

    /**
     * 
     * @param getItemShippingRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetItemShippingResponseType
     */
    @WebMethod(operationName = "GetItemShipping")
    @WebResult(name = "GetItemShippingResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetItemShippingResponse")
    public GetItemShippingResponseType getItemShipping(
        @WebParam(name = "GetItemShippingRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetItemShippingRequest")
        GetItemShippingRequestType getItemShippingRequest);

    /**
     * 
     * @param getItemTransactionsRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetItemTransactionsResponseType
     */
    @WebMethod(operationName = "GetItemTransactions")
    @WebResult(name = "GetItemTransactionsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetItemTransactionsResponse")
    public GetItemTransactionsResponseType getItemTransactions(
        @WebParam(name = "GetItemTransactionsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetItemTransactionsRequest")
        GetItemTransactionsRequestType getItemTransactionsRequest);

    /**
     * 
     * @param getItemsAwaitingFeedbackRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetItemsAwaitingFeedbackResponseType
     */
    @WebMethod(operationName = "GetItemsAwaitingFeedback")
    @WebResult(name = "GetItemsAwaitingFeedbackResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetItemsAwaitingFeedbackResponse")
    public GetItemsAwaitingFeedbackResponseType getItemsAwaitingFeedback(
        @WebParam(name = "GetItemsAwaitingFeedbackRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetItemsAwaitingFeedbackRequest")
        GetItemsAwaitingFeedbackRequestType getItemsAwaitingFeedbackRequest);

    /**
     * 
     * @param getMemberMessagesRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetMemberMessagesResponseType
     */
    @WebMethod(operationName = "GetMemberMessages")
    @WebResult(name = "GetMemberMessagesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetMemberMessagesResponse")
    public GetMemberMessagesResponseType getMemberMessages(
        @WebParam(name = "GetMemberMessagesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetMemberMessagesRequest")
        GetMemberMessagesRequestType getMemberMessagesRequest);

    /**
     * 
     * @param getMessagePreferencesRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetMessagePreferencesResponseType
     */
    @WebMethod(operationName = "GetMessagePreferences")
    @WebResult(name = "GetMessagePreferencesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetMessagePreferencesResponse")
    public GetMessagePreferencesResponseType getMessagePreferences(
        @WebParam(name = "GetMessagePreferencesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetMessagePreferencesRequest")
        GetMessagePreferencesRequestType getMessagePreferencesRequest);

    /**
     * 
     * @param getMyMessagesRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetMyMessagesResponseType
     */
    @WebMethod(operationName = "GetMyMessages")
    @WebResult(name = "GetMyMessagesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetMyMessagesResponse")
    public GetMyMessagesResponseType getMyMessages(
        @WebParam(name = "GetMyMessagesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetMyMessagesRequest")
        GetMyMessagesRequestType getMyMessagesRequest);

    /**
     * 
     * @param getMyeBayBuyingRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetMyeBayBuyingResponseType
     */
    @WebMethod(operationName = "GetMyeBayBuying")
    @WebResult(name = "GetMyeBayBuyingResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetMyeBayBuyingResponse")
    public GetMyeBayBuyingResponseType getMyeBayBuying(
        @WebParam(name = "GetMyeBayBuyingRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetMyeBayBuyingRequest")
        GetMyeBayBuyingRequestType getMyeBayBuyingRequest);

    /**
     * 
     * @param getMyeBaySellingRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetMyeBaySellingResponseType
     */
    @WebMethod(operationName = "GetMyeBaySelling")
    @WebResult(name = "GetMyeBaySellingResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetMyeBaySellingResponse")
    public GetMyeBaySellingResponseType getMyeBaySelling(
        @WebParam(name = "GetMyeBaySellingRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetMyeBaySellingRequest")
        GetMyeBaySellingRequestType getMyeBaySellingRequest);

    /**
     * 
     * @param getNotificationPreferencesRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetNotificationPreferencesResponseType
     */
    @WebMethod(operationName = "GetNotificationPreferences")
    @WebResult(name = "GetNotificationPreferencesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetNotificationPreferencesResponse")
    public GetNotificationPreferencesResponseType getNotificationPreferences(
        @WebParam(name = "GetNotificationPreferencesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetNotificationPreferencesRequest")
        GetNotificationPreferencesRequestType getNotificationPreferencesRequest);

    /**
     * 
     * @param getNotificationsUsageRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetNotificationsUsageResponseType
     */
    @WebMethod(operationName = "GetNotificationsUsage")
    @WebResult(name = "GetNotificationsUsageResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetNotificationsUsageResponse")
    public GetNotificationsUsageResponseType getNotificationsUsage(
        @WebParam(name = "GetNotificationsUsageRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetNotificationsUsageRequest")
        GetNotificationsUsageRequestType getNotificationsUsageRequest);

    /**
     * 
     * @param getOrdersRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetOrdersResponseType
     */
    @WebMethod(operationName = "GetOrders")
    @WebResult(name = "GetOrdersResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetOrdersResponse")
    public GetOrdersResponseType getOrders(
        @WebParam(name = "GetOrdersRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetOrdersRequest")
        GetOrdersRequestType getOrdersRequest);

    /**
     * 
     * @param getSellerEventsRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetSellerEventsResponseType
     */
    @WebMethod(operationName = "GetSellerEvents")
    @WebResult(name = "GetSellerEventsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetSellerEventsResponse")
    public GetSellerEventsResponseType getSellerEvents(
        @WebParam(name = "GetSellerEventsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetSellerEventsRequest")
        GetSellerEventsRequestType getSellerEventsRequest);

    /**
     * 
     * @param getSellerListRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetSellerListResponseType
     */
    @WebMethod(operationName = "GetSellerList")
    @WebResult(name = "GetSellerListResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetSellerListResponse")
    public GetSellerListResponseType getSellerList(
        @WebParam(name = "GetSellerListRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetSellerListRequest")
        GetSellerListRequestType getSellerListRequest);

    /**
     * 
     * @param getSellerTransactionsRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetSellerTransactionsResponseType
     */
    @WebMethod(operationName = "GetSellerTransactions")
    @WebResult(name = "GetSellerTransactionsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetSellerTransactionsResponse")
    public GetSellerTransactionsResponseType getSellerTransactions(
        @WebParam(name = "GetSellerTransactionsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetSellerTransactionsRequest")
        GetSellerTransactionsRequestType getSellerTransactionsRequest);

    /**
     * 
     * @param getSessionIDRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetSessionIDResponseType
     */
    @WebMethod(operationName = "GetSessionID")
    @WebResult(name = "GetSessionIDResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetSessionIDResponse")
    public GetSessionIDResponseType getSessionID(
        @WebParam(name = "GetSessionIDRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetSessionIDRequest")
        GetSessionIDRequestType getSessionIDRequest);

    /**
     * 
     * @param getShippingDiscountProfilesRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetShippingDiscountProfilesResponseType
     */
    @WebMethod(operationName = "GetShippingDiscountProfiles")
    @WebResult(name = "GetShippingDiscountProfilesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetShippingDiscountProfilesResponse")
    public GetShippingDiscountProfilesResponseType getShippingDiscountProfiles(
        @WebParam(name = "GetShippingDiscountProfilesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetShippingDiscountProfilesRequest")
        GetShippingDiscountProfilesRequestType getShippingDiscountProfilesRequest);

    /**
     * 
     * @param getStoreRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetStoreResponseType
     */
    @WebMethod(operationName = "GetStore")
    @WebResult(name = "GetStoreResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetStoreResponse")
    public GetStoreResponseType getStore(
        @WebParam(name = "GetStoreRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetStoreRequest")
        GetStoreRequestType getStoreRequest);

    /**
     * 
     * @param getStoreCategoryUpdateStatusRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetStoreCategoryUpdateStatusResponseType
     */
    @WebMethod(operationName = "GetStoreCategoryUpdateStatus")
    @WebResult(name = "GetStoreCategoryUpdateStatusResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetStoreCategoryUpdateStatusResponse")
    public GetStoreCategoryUpdateStatusResponseType getStoreCategoryUpdateStatus(
        @WebParam(name = "GetStoreCategoryUpdateStatusRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetStoreCategoryUpdateStatusRequest")
        GetStoreCategoryUpdateStatusRequestType getStoreCategoryUpdateStatusRequest);

    /**
     * 
     * @param getTaxTableRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetTaxTableResponseType
     */
    @WebMethod(operationName = "GetTaxTable")
    @WebResult(name = "GetTaxTableResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetTaxTableResponse")
    public GetTaxTableResponseType getTaxTable(
        @WebParam(name = "GetTaxTableRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetTaxTableRequest")
        GetTaxTableRequestType getTaxTableRequest);

    /**
     * 
     * @param getTokenStatusRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetTokenStatusResponseType
     */
    @WebMethod(operationName = "GetTokenStatus")
    @WebResult(name = "GetTokenStatusResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetTokenStatusResponse")
    public GetTokenStatusResponseType getTokenStatus(
        @WebParam(name = "GetTokenStatusRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetTokenStatusRequest")
        GetTokenStatusRequestType getTokenStatusRequest);

    /**
     * 
     * @param getUserRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetUserResponseType
     */
    @WebMethod(operationName = "GetUser")
    @WebResult(name = "GetUserResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetUserResponse")
    public GetUserResponseType getUser(
        @WebParam(name = "GetUserRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetUserRequest")
        GetUserRequestType getUserRequest);

    /**
     * 
     * @param getUserContactDetailsRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetUserContactDetailsResponseType
     */
    @WebMethod(operationName = "GetUserContactDetails")
    @WebResult(name = "GetUserContactDetailsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetUserContactDetailsResponse")
    public GetUserContactDetailsResponseType getUserContactDetails(
        @WebParam(name = "GetUserContactDetailsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetUserContactDetailsRequest")
        GetUserContactDetailsRequestType getUserContactDetailsRequest);

    /**
     * 
     * @param getUserPreferencesRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetUserPreferencesResponseType
     */
    @WebMethod(operationName = "GetUserPreferences")
    @WebResult(name = "GetUserPreferencesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetUserPreferencesResponse")
    public GetUserPreferencesResponseType getUserPreferences(
        @WebParam(name = "GetUserPreferencesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetUserPreferencesRequest")
        GetUserPreferencesRequestType getUserPreferencesRequest);

    /**
     * 
     * @param getVeROReasonCodeDetailsRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetVeROReasonCodeDetailsResponseType
     */
    @WebMethod(operationName = "GetVeROReasonCodeDetails")
    @WebResult(name = "GetVeROReasonCodeDetailsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetVeROReasonCodeDetailsResponse")
    public GetVeROReasonCodeDetailsResponseType getVeROReasonCodeDetails(
        @WebParam(name = "GetVeROReasonCodeDetailsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetVeROReasonCodeDetailsRequest")
        GetVeROReasonCodeDetailsRequestType getVeROReasonCodeDetailsRequest);

    /**
     * 
     * @param getVeROReportStatusRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GetVeROReportStatusResponseType
     */
    @WebMethod(operationName = "GetVeROReportStatus")
    @WebResult(name = "GetVeROReportStatusResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetVeROReportStatusResponse")
    public GetVeROReportStatusResponseType getVeROReportStatus(
        @WebParam(name = "GetVeROReportStatusRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetVeROReportStatusRequest")
        GetVeROReportStatusRequestType getVeROReportStatusRequest);

    /**
     * 
     * @param geteBayDetailsRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GeteBayDetailsResponseType
     */
    @WebMethod(operationName = "GeteBayDetails")
    @WebResult(name = "GeteBayDetailsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GeteBayDetailsResponse")
    public GeteBayDetailsResponseType geteBayDetails(
        @WebParam(name = "GeteBayDetailsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GeteBayDetailsRequest")
        GeteBayDetailsRequestType geteBayDetailsRequest);

    /**
     * 
     * @param geteBayOfficialTimeRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.GeteBayOfficialTimeResponseType
     */
    @WebMethod(operationName = "GeteBayOfficialTime")
    @WebResult(name = "GeteBayOfficialTimeResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GeteBayOfficialTimeResponse")
    public GeteBayOfficialTimeResponseType geteBayOfficialTime(
        @WebParam(name = "GeteBayOfficialTimeRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GeteBayOfficialTimeRequest")
        GeteBayOfficialTimeRequestType geteBayOfficialTimeRequest);

    /**
     * 
     * @param leaveFeedbackRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.LeaveFeedbackResponseType
     */
    @WebMethod(operationName = "LeaveFeedback")
    @WebResult(name = "LeaveFeedbackResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "LeaveFeedbackResponse")
    public LeaveFeedbackResponseType leaveFeedback(
        @WebParam(name = "LeaveFeedbackRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "LeaveFeedbackRequest")
        LeaveFeedbackRequestType leaveFeedbackRequest);

    /**
     * 
     * @param placeOfferRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.PlaceOfferResponseType
     */
    @WebMethod(operationName = "PlaceOffer")
    @WebResult(name = "PlaceOfferResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "PlaceOfferResponse")
    public PlaceOfferResponseType placeOffer(
        @WebParam(name = "PlaceOfferRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "PlaceOfferRequest")
        PlaceOfferRequestType placeOfferRequest);

    /**
     * 
     * @param relistFixedPriceItemRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.RelistFixedPriceItemResponseType
     */
    @WebMethod(operationName = "RelistFixedPriceItem")
    @WebResult(name = "RelistFixedPriceItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "RelistFixedPriceItemResponse")
    public RelistFixedPriceItemResponseType relistFixedPriceItem(
        @WebParam(name = "RelistFixedPriceItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "RelistFixedPriceItemRequest")
        RelistFixedPriceItemRequestType relistFixedPriceItemRequest);

    /**
     * 
     * @param relistItemRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.RelistItemResponseType
     */
    @WebMethod(operationName = "RelistItem")
    @WebResult(name = "RelistItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "RelistItemResponse")
    public RelistItemResponseType relistItem(
        @WebParam(name = "RelistItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "RelistItemRequest")
        RelistItemRequestType relistItemRequest);

    /**
     * 
     * @param removeFromWatchListRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.RemoveFromWatchListResponseType
     */
    @WebMethod(operationName = "RemoveFromWatchList")
    @WebResult(name = "RemoveFromWatchListResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "RemoveFromWatchListResponse")
    public RemoveFromWatchListResponseType removeFromWatchList(
        @WebParam(name = "RemoveFromWatchListRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "RemoveFromWatchListRequest")
        RemoveFromWatchListRequestType removeFromWatchListRequest);

    /**
     * 
     * @param respondToBestOfferRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.RespondToBestOfferResponseType
     */
    @WebMethod(operationName = "RespondToBestOffer")
    @WebResult(name = "RespondToBestOfferResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "RespondToBestOfferResponse")
    public RespondToBestOfferResponseType respondToBestOffer(
        @WebParam(name = "RespondToBestOfferRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "RespondToBestOfferRequest")
        RespondToBestOfferRequestType respondToBestOfferRequest);

    /**
     * 
     * @param respondToFeedbackRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.RespondToFeedbackResponseType
     */
    @WebMethod(operationName = "RespondToFeedback")
    @WebResult(name = "RespondToFeedbackResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "RespondToFeedbackResponse")
    public RespondToFeedbackResponseType respondToFeedback(
        @WebParam(name = "RespondToFeedbackRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "RespondToFeedbackRequest")
        RespondToFeedbackRequestType respondToFeedbackRequest);

    /**
     * 
     * @param reviseFixedPriceItemRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.ReviseFixedPriceItemResponseType
     */
    @WebMethod(operationName = "ReviseFixedPriceItem")
    @WebResult(name = "ReviseFixedPriceItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ReviseFixedPriceItemResponse")
    public ReviseFixedPriceItemResponseType reviseFixedPriceItem(
        @WebParam(name = "ReviseFixedPriceItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ReviseFixedPriceItemRequest")
        ReviseFixedPriceItemRequestType reviseFixedPriceItemRequest);

    /**
     * 
     * @param reviseInventoryStatusRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.ReviseInventoryStatusResponseType
     */
    @WebMethod(operationName = "ReviseInventoryStatus")
    @WebResult(name = "ReviseInventoryStatusResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ReviseInventoryStatusResponse")
    public ReviseInventoryStatusResponseType reviseInventoryStatus(
        @WebParam(name = "ReviseInventoryStatusRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ReviseInventoryStatusRequest")
        ReviseInventoryStatusRequestType reviseInventoryStatusRequest);

    /**
     * 
     * @param reviseItemRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.ReviseItemResponseType
     */
    @WebMethod(operationName = "ReviseItem")
    @WebResult(name = "ReviseItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ReviseItemResponse")
    public ReviseItemResponseType reviseItem(
        @WebParam(name = "ReviseItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ReviseItemRequest")
        ReviseItemRequestType reviseItemRequest);

    /**
     * 
     * @param reviseMyMessagesRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.ReviseMyMessagesResponseType
     */
    @WebMethod(operationName = "ReviseMyMessages")
    @WebResult(name = "ReviseMyMessagesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ReviseMyMessagesResponse")
    public ReviseMyMessagesResponseType reviseMyMessages(
        @WebParam(name = "ReviseMyMessagesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ReviseMyMessagesRequest")
        ReviseMyMessagesRequestType reviseMyMessagesRequest);

    /**
     * 
     * @param reviseMyMessagesFoldersRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.ReviseMyMessagesFoldersResponseType
     */
    @WebMethod(operationName = "ReviseMyMessagesFolders")
    @WebResult(name = "ReviseMyMessagesFoldersResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ReviseMyMessagesFoldersResponse")
    public ReviseMyMessagesFoldersResponseType reviseMyMessagesFolders(
        @WebParam(name = "ReviseMyMessagesFoldersRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ReviseMyMessagesFoldersRequest")
        ReviseMyMessagesFoldersRequestType reviseMyMessagesFoldersRequest);

    /**
     * 
     * @param revokeTokenRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.RevokeTokenResponseType
     */
    @WebMethod(operationName = "RevokeToken")
    @WebResult(name = "RevokeTokenResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "RevokeTokenResponse")
    public RevokeTokenResponseType revokeToken(
        @WebParam(name = "RevokeTokenRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "RevokeTokenRequest")
        RevokeTokenRequestType revokeTokenRequest);

    /**
     * 
     * @param sendInvoiceRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.SendInvoiceResponseType
     */
    @WebMethod(operationName = "SendInvoice")
    @WebResult(name = "SendInvoiceResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SendInvoiceResponse")
    public SendInvoiceResponseType sendInvoice(
        @WebParam(name = "SendInvoiceRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SendInvoiceRequest")
        SendInvoiceRequestType sendInvoiceRequest);

    /**
     * 
     * @param setMessagePreferencesRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.SetMessagePreferencesResponseType
     */
    @WebMethod(operationName = "SetMessagePreferences")
    @WebResult(name = "SetMessagePreferencesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetMessagePreferencesResponse")
    public SetMessagePreferencesResponseType setMessagePreferences(
        @WebParam(name = "SetMessagePreferencesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetMessagePreferencesRequest")
        SetMessagePreferencesRequestType setMessagePreferencesRequest);

    /**
     * 
     * @param setNotificationPreferencesRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.SetNotificationPreferencesResponseType
     */
    @WebMethod(operationName = "SetNotificationPreferences")
    @WebResult(name = "SetNotificationPreferencesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetNotificationPreferencesResponse")
    public SetNotificationPreferencesResponseType setNotificationPreferences(
        @WebParam(name = "SetNotificationPreferencesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetNotificationPreferencesRequest")
        SetNotificationPreferencesRequestType setNotificationPreferencesRequest);

    /**
     * 
     * @param setShippingDiscountProfilesRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.SetShippingDiscountProfilesResponseType
     */
    @WebMethod(operationName = "SetShippingDiscountProfiles")
    @WebResult(name = "SetShippingDiscountProfilesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetShippingDiscountProfilesResponse")
    public SetShippingDiscountProfilesResponseType setShippingDiscountProfiles(
        @WebParam(name = "SetShippingDiscountProfilesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetShippingDiscountProfilesRequest")
        SetShippingDiscountProfilesRequestType setShippingDiscountProfilesRequest);

    /**
     * 
     * @param setStoreCategoriesRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.SetStoreCategoriesResponseType
     */
    @WebMethod(operationName = "SetStoreCategories")
    @WebResult(name = "SetStoreCategoriesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetStoreCategoriesResponse")
    public SetStoreCategoriesResponseType setStoreCategories(
        @WebParam(name = "SetStoreCategoriesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetStoreCategoriesRequest")
        SetStoreCategoriesRequestType setStoreCategoriesRequest);

    /**
     * 
     * @param setTaxTableRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.SetTaxTableResponseType
     */
    @WebMethod(operationName = "SetTaxTable")
    @WebResult(name = "SetTaxTableResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetTaxTableResponse")
    public SetTaxTableResponseType setTaxTable(
        @WebParam(name = "SetTaxTableRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetTaxTableRequest")
        SetTaxTableRequestType setTaxTableRequest);

    /**
     * 
     * @param setUserNotesRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.SetUserNotesResponseType
     */
    @WebMethod(operationName = "SetUserNotes")
    @WebResult(name = "SetUserNotesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetUserNotesResponse")
    public SetUserNotesResponseType setUserNotes(
        @WebParam(name = "SetUserNotesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetUserNotesRequest")
        SetUserNotesRequestType setUserNotesRequest);

    /**
     * 
     * @param setUserPreferencesRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.SetUserPreferencesResponseType
     */
    @WebMethod(operationName = "SetUserPreferences")
    @WebResult(name = "SetUserPreferencesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetUserPreferencesResponse")
    public SetUserPreferencesResponseType setUserPreferences(
        @WebParam(name = "SetUserPreferencesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetUserPreferencesRequest")
        SetUserPreferencesRequestType setUserPreferencesRequest);

    /**
     * 
     * @param uploadSiteHostedPicturesRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.UploadSiteHostedPicturesResponseType
     */
    @WebMethod(operationName = "UploadSiteHostedPictures")
    @WebResult(name = "UploadSiteHostedPicturesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "UploadSiteHostedPicturesResponse")
    public UploadSiteHostedPicturesResponseType uploadSiteHostedPictures(
        @WebParam(name = "UploadSiteHostedPicturesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "UploadSiteHostedPicturesRequest")
        UploadSiteHostedPicturesRequestType uploadSiteHostedPicturesRequest);

    /**
     * 
     * @param validateChallengeInputRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.ValidateChallengeInputResponseType
     */
    @WebMethod(operationName = "ValidateChallengeInput")
    @WebResult(name = "ValidateChallengeInputResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ValidateChallengeInputResponse")
    public ValidateChallengeInputResponseType validateChallengeInput(
        @WebParam(name = "ValidateChallengeInputRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ValidateChallengeInputRequest")
        ValidateChallengeInputRequestType validateChallengeInputRequest);

    /**
     * 
     * @param validateTestUserRegistrationRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.ValidateTestUserRegistrationResponseType
     */
    @WebMethod(operationName = "ValidateTestUserRegistration")
    @WebResult(name = "ValidateTestUserRegistrationResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ValidateTestUserRegistrationResponse")
    public ValidateTestUserRegistrationResponseType validateTestUserRegistration(
        @WebParam(name = "ValidateTestUserRegistrationRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ValidateTestUserRegistrationRequest")
        ValidateTestUserRegistrationRequestType validateTestUserRegistrationRequest);

    /**
     * 
     * @param veROReportItemsRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.VeROReportItemsResponseType
     */
    @WebMethod(operationName = "VeROReportItems")
    @WebResult(name = "VeROReportItemsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "VeROReportItemsResponse")
    public VeROReportItemsResponseType veROReportItems(
        @WebParam(name = "VeROReportItemsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "VeROReportItemsRequest")
        VeROReportItemsRequestType veROReportItemsRequest);

    /**
     * 
     * @param verifyAddFixedPriceItemRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.VerifyAddFixedPriceItemResponseType
     */
    @WebMethod(operationName = "VerifyAddFixedPriceItem")
    @WebResult(name = "VerifyAddFixedPriceItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "VerifyAddFixedPriceItemResponse")
    public VerifyAddFixedPriceItemResponseType verifyAddFixedPriceItem(
        @WebParam(name = "VerifyAddFixedPriceItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "VerifyAddFixedPriceItemRequest")
        VerifyAddFixedPriceItemRequestType verifyAddFixedPriceItemRequest);

    /**
     * 
     * @param verifyAddItemRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.VerifyAddItemResponseType
     */
    @WebMethod(operationName = "VerifyAddItem")
    @WebResult(name = "VerifyAddItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "VerifyAddItemResponse")
    public VerifyAddItemResponseType verifyAddItem(
        @WebParam(name = "VerifyAddItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "VerifyAddItemRequest")
        VerifyAddItemRequestType verifyAddItemRequest);

    /**
     * 
     * @param verifyAddSecondChanceItemRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.VerifyAddSecondChanceItemResponseType
     */
    @WebMethod(operationName = "VerifyAddSecondChanceItem")
    @WebResult(name = "VerifyAddSecondChanceItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "VerifyAddSecondChanceItemResponse")
    public VerifyAddSecondChanceItemResponseType verifyAddSecondChanceItem(
        @WebParam(name = "VerifyAddSecondChanceItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "VerifyAddSecondChanceItemRequest")
        VerifyAddSecondChanceItemRequestType verifyAddSecondChanceItemRequest);

    /**
     * 
     * @param verifyRelistItemRequest
     * @return
     *     returns com.ebay.soap.eBLBaseComponents.VerifyRelistItemResponseType
     */
    @WebMethod(operationName = "VerifyRelistItem")
    @WebResult(name = "VerifyRelistItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "VerifyRelistItemResponse")
    public VerifyRelistItemResponseType verifyRelistItem(
        @WebParam(name = "VerifyRelistItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "VerifyRelistItemRequest")
        VerifyRelistItemRequestType verifyRelistItemRequest);

}
